### ISSUE TITLE
Add schema for YAML syntax ease rule writing 

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/semgrep-vscode#1]
I came across this tool https://github.com/Threagile/threagile that lets you write threat models in YAML. It also has a YAML schema that lets you lint keys/values (if there are specific allowable values).

Would be nice to have similar functionality for writing Semgrep rules.

**Comment by ajbt200128** [comment]
Replying for visibility, we also have a schema! To get autocomplete in yaml files:

1. Install [this extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
2. add the following to `settings.json`
```
    "yaml.schemas": {
        "https://json.schemastore.org/semgrep.json":"/**/{semgrep,.semgrep}.{yml,yaml}"
    }
```
