### ISSUE TITLE
Use .semgrep.yml when present?

### ISSUE THREAD

**Issue by Strajk** [returntocorp/semgrep-vscode#14]

**Comment by Strajk** [comment]
I've inspected the code and realized that the value from `config.rules` in simply passed to `--config`, so I can just set the value to local file, and not url to published semgrep config :))

![image](https://user-images.githubusercontent.com/697301/119562041-30731000-bda6-11eb-8e14-5484a339fda6.png)

:yay:

**Comment by underyx** [comment]
:yay:

Sorry I didn't think of this solution for you earlier!

**Comment by ajbt200128** [comment]
Closed in 5659. Any file in the form of starting with `semgrep` or `.semgrep` and ending with `.yaml` or `.yml` will be autodetected and used
