### ISSUE TITLE
can not find semgrep installed by pip in WSL

### ISSUE THREAD

**Issue by tuhaolam** [returntocorp/semgrep-vscode#15]
![image](https://user-images.githubusercontent.com/10894348/118769235-8893a900-b8b2-11eb-962a-564da34eb3de.png)

```
Semgrep is not installed, try running `pip install semgrep`. Linting will be disabled until restart.
```

**Comment by Spencer-Dawson** [comment]
95% certain this is a Duplicate of #12 
I'm seeing this as well.

**Comment by ajbt200128** [comment]
See closing comment of #12! Feel free to re-open if that isn't a solution
