### ISSUE TITLE
Visual Studio Code - Code Actions

### ISSUE THREAD

**Issue by zythosec** [returntocorp/semgrep-vscode#2]
Visual Studio Code has a feature called Code Actions, which can provide both refactorings and quick fixes for detected issues: https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings

As a semgrep-vscode user, I would like the ability to not only receive suggestions from the semgrep extension, but to have the extension **_automatically fix the problematic code_** as well. An example of where these quick fixes or refactorings show up is in the tool tip when semgrep reports an issue on a piece of code (currently there are no quick fixes available): 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2287187/90256611-f71f7400-de13-11ea-8351-ebc7e183902b.png">

**Additional Documentation**
VS Code API Documentation: https://vscode-docs.readthedocs.io/en/stable/extensionAPI/vscode-api/#CodeActionProvider
Language Extension Documentation: https://code.visualstudio.com/api/language-extensions/programmatic-language-features#possible-actions-on-errors-or-warnings
Sample Code Action Provider: https://github.com/microsoft/vscode-extension-samples/tree/master/code-actions-sample

**Comment by underyx** [comment]
Wow @zythosec, that's super detailed, thanks so much!

**Comment by NoamNol** [comment]
Any update?

**Comment by underyx** [comment]
Hey @NoamNol, thanks for the interest. I did play around with this last year but never finished up the work: https://github.com/returntocorp/semgrep-vscode/pull/10

Also, this project is still experimental and doesn't have staffing at the moment. Do feel free to take a stab at this feature though!

**Comment by ajbt200128** [comment]
Closed by #19
