### ISSUE TITLE
[Feature request] Allow users to pass additional flags

### ISSUE THREAD

**Issue by pm98zz-c** [returntocorp/semgrep-vscode#20]
I tend to run semgrep in "--strict" mode, which is currently not possible in the vscode extension. It would be useful to be able to pass additional flags (others might have other use cases than just "--strict").

Example syntax from the Go extension (https://golangci-lint.run/usage/integrations/):
´´´
"go.lintTool":"golangci-lint",
"go.lintFlags": [
  "--fast"
]
```

**Comment by ajbt200128** [comment]
Closed by returntocorp/semgrep#5659. We now support configuring all (relevant) CLI flags in the extension settings. If there's some flag you were expecting to see but it's not there, feel free to open a new issue!
