### ISSUE TITLE
Support semgrep installed via brew

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep-vscode#3]
the extension does not work if semgrep is installed via brew instead of pip

**Comment by ryansb** [comment]
I'm on MacOS 11.2.2 and this works with brew-installed semgrep for me.

**Comment by dgryski** [comment]
I think is because of my PATH and how I start vscode.  When run from the terminal, my PATH has /usr/local/bin so the semgrep installed there is found.  When run from the dock or spotlight, it doesn't.

**Comment by ajbt200128** [comment]
Looks like this was closed in https://github.com/returntocorp/semgrep-vscode/pull/18
