### ISSUE TITLE
"Only git dirty" option doesn't work

### ISSUE THREAD

**Issue by josepjaume** [returntocorp/semgrep-vscode#38]
Semgrepping changes doesn't work on the latest version (1.2.0). However, disabling the "Only git dirty" option does work - although it loads the entire workspace and takes quite a while to load.

I don't see any error message on the extension's output. I can't see any error regardless of the file being saved or only changed in the editor.

**Comment by josepjaume** [comment]
To add a bit more context: I'm working on a multi-workspace project, and the "Scan changed files" doesn't seem to do anything 👀

**Comment by ajbt200128** [comment]
Hmm, it may be an issue with multiworkspace projects. When running the CLI or extension on any workspace, if the top level directory is not a git repo, semgrep will default to scanning all files regardless of their git status, or git ignore status, and this can take a long time (a few minutes), if there's a lot. I'd say try opening a single workspace/repository, and see if you're still getting the same issue.

**Comment by josepjaume** [comment]
Thanks, will do! 👍

**Comment by josepjaume** [comment]
I checked and that seems to be the case. So, to be clear, I have a project configured such as this:

```json
# workspace.code-workspace
{
  "folders": [
    {
      "name": "Backend",
      "path": "backend"
    },
    {
      "name": "Frontend",
      "path": "frontend"
    }
 }
```

Both `backend` and `frontend` are folders inside a git repo. Looking for changed files doesn't work. As you mentioned, I believe the issue is that is not correctly detecting the git repository as it assumes it's going to be in the root of the project, but it needs to recursively go up until it finds one.

How can I help fix this? Any pointers to the relevant code?

Thanks for the great work!

**Comment by ajbt200128** [comment]
>  Enabling "Only git dirty" doesn't work - however, it used to work before the last update.

Pre version 1.0.0, the LSP was implemented very differently, and ultimately wasn't very maintainable in that state. 

> As you mentioned, I believe the issue is that is not correctly detecting the git repository as it assumes it's going to be in the root of the project, but it needs to recursively go up until it finds one.

Yup this is exactly the issue judging by your config

> How can I help fix this? Any pointers to the relevant code?

Always happy to accept contributions, the changes you'd want to make would be on [the semgrep CLI side](https://github.com/returntocorp/semgrep/tree/develop/src/language_server), specifically when we check git status, and make that relative to workspace folders. I don't think this will be a quick fix though, and we do have plans to get to it eventually, but feel free to take a crack at it if you want!
