### ISSUE TITLE
Extension unexpectedly doesn't run generic rules

### ISSUE THREAD

**Issue by underyx** [returntocorp/semgrep-vscode#4]
The `semgrep.languages` option has a hardcoded list of languages the extension should activate on. We say that "by default, this is set to all supported languages".

This however isn't entirely true, because some Semgrep rules exist for languages that are not in our official supported languages list, such as pure regex rules for templating languages. We had a difficult-to-debug case of this on the community Slack: https://r2c-community.slack.com/archives/C01911CD53K/p1605701977013300?thread_ts=1605612969.007800&cid=C01911CD53K

We could make Semgrep always run, but this might be annoying for users that work in unsupported languages, as Semgrep would run in the background on every save even if it has no chance of finding any results.

We could set up some kind of release process to always bring in every language identifier that has a rule in the registry, which to a lesser extent can still be annoying like above. But this will be useful in other cases as well; the extension didn't run on TS/TSX for months because we forgot we had to manually add the language ID in the extension when semgrep started supporting these languages.

We could try to infer all languages to be scanned from the selected config value, but this would be complicated to code and might be a brittle, or even impossible approach.

**Comment by ajbt200128** [comment]
Extension now mirrors CLI functionality wherein generic rules will run if using config auto, they are configured in the app, or added as a config option
