### ISSUE TITLE
There should be some visual feedback when Semgrep finished scanning successfully

### ISSUE THREAD

**Issue by underyx** [returntocorp/semgrep-vscode#6]

**Comment by Strajk** [comment]
Maybe even indicator that scanning is in progress - would be useful when debugging extension settings

**Comment by ajbt200128** [comment]
This can easily be added to the LSP with [this method](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_workDoneProgress_create)

**Comment by ajbt200128** [comment]
Closed in #5659
