### ISSUE TITLE
Exploring using Semgrep in Vscode through Docker

### ISSUE THREAD

**Issue by drewbitt** [returntocorp/semgrep-vscode#61]
Obviously, semgrep does not work for Windows. And even if you install semgrep in WSL, if you attempt to set the path to Semgrep in the VSCode on Windows (not WSL) with something like `\\wsl.localhost\Ubuntu-22.04\home\drewbitt\.local\bin\semgrep`, it won't work as it's a Linux binary.

Therefore, the remaining option for a Windows solution (which doesn't revert all code/other extension execution to WSL i.e. a WSL Dev Container) would be through Docker. The existing Docker of Semgrep only supports scanning a single volume at a time and is not a continuous binary that is exposed via a port. But as this is the only possible way that semgrep can run on Windows for now, I am curious if connecting the extension to a Docker instance is a viable option/direction that the team would be interested in exploring.

**Comment by ajbt200128** [comment]
Currently we don't have any plans to support Windows, or packaging the language server in a Dockerfile. One thing you could try is using Dev Containers, and adding the semgrep extension to your configuration, though I haven't tried it myself. See [here](https://code.visualstudio.com/docs/devcontainers/containers#_create-a-devcontainerjson-file)

**Comment by drewbitt** [comment]
That looks like an option as long as #58 is not a problem, although annoying to do just for semgrep. Looking forward to whenever you decide to branch out to Windows.
