### ISSUE TITLE
Extension not running after latest Semgrep update

### ISSUE THREAD

**Issue by navhits** [returntocorp/semgrep-vscode#67]
I updated to the latest Semgrep version 1.35.0. After this, the plugin crashes with this error. 
<img width="461" alt="Screenshot 2023-08-16 at 3 03 32 PM" src="https://github.com/returntocorp/semgrep-vscode/assets/22239584/11507311-a164-45ff-9e3d-224ddfd984eb">

Semgrep was installed with homebrew. I did not try installing it with pip yet.

OS: MacOS 13
Machine: Macbook M1 pro
VS Code version: 1.81.1 (regular build)

**Comment by ajbt200128** [comment]
Hi Naveen, this bug should be fixed in 1.36.0, going to close this issue, but if it still persists feel free to reopen!

**Comment by navhits** [comment]
Yes its working now. Thanks
