### ISSUE TITLE
semgrep v1.5.2 for vscode is not working at all

### ISSUE THREAD

**Issue by CaledoniaProject** [returntocorp/semgrep-vscode#72]
I've installed semgrep v1.5.2 in VSCode. Then I configured a directory of rules. These rules works fine with `semgrep --config XXX project-root/`

![shot 2023-09-17 at 13 47 41](https://github.com/returntocorp/semgrep/assets/1357701/83a38280-6cf2-4339-8f18-a14333a02240)

Then I opened the project folder and use `Semgrep: Scan all files in workspace` to scan it:

![shot 2023-09-17 at 13 48 12](https://github.com/returntocorp/semgrep/assets/1357701/bd211f0f-84a3-43df-a61f-3faeec1115ce)

It's finished but no result is visible in the tab:

![shot 2023-09-17 at 13 49 01](https://github.com/returntocorp/semgrep/assets/1357701/53230461-638c-47a1-a9ba-732e29ac8184)

What's wrong?

**Comment by ajbt200128** [comment]
Hi, the search tab is for results after running "Semgrep Search by pattern". A full scan will show findings in the problems tab. Feel free to reopen if there's findings you're expecting there

**Comment by CaledoniaProject** [comment]
@ajbt200128 I want to scan the code with my rules directory, where should I see the results then?

**Comment by ajbt200128** [comment]
@CaledoniaProject in your configuration settings (shown above), you'll have to add each rules file as an item in this setting, and then restart VSCode

**Comment by CaledoniaProject** [comment]
@ajbt200128 That would be a very bad user experience. The cli program can load rules from a directory, why won't you support this feature in vscode?

**Comment by ajbt200128** [comment]
The plugin is partly a separate code base from Semgrep, and so has a slightly separate feature set. We'll try and add this to our roadmap, but we're not currently planning support
