### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by msorens** [returntocorp/semgrep-vscode#8]
These two lines... are actually a big impediment to actually using the extension:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/6817500/110048513-d44ba300-7d04-11eb-9f74-8346cf611b5d.png">

(The above--essentially the sum total of the documentation for the plugin, not counting the config details--is what you see on the plugin page when installed in VSCode.)
Seeing that only left me with questions:
 * How do you run a scan?
 * Where are the results reported? 
 * How do I generate search patterns?
 * Why would one want to?

Things that need to be added:
1. Semgrep runs a scan on Save.
2. Results are reported in two places: squiggles under the code and itemized in the Problems pane.
3. Open VSCode's command palette <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and type "semgrep" to see the available actions to generate search patterns.
4. When you run the "Suggest Semgrep Patterns for..." action, you have to first select an "interesting" line or lines of code; some things will just report "No pattern suggestions for your selected code". [And when you see this on the very first attempt of using it, you wonder what to do next.] So an example would be quite helpful.

**Comment by msorens** [comment]
One more interesting case that definitely needs mentioning. I invoked "Suggest Semgrep Patterns for Line" from the command palette on the line shown and got this quite cryptic response:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/6817500/110572966-4827ea00-810f-11eb-9ac7-40b1177fd90e.png">

For someone just getting started, that will evoke a definite "Huh?!?"
In case you need the piece of code to to try that on it is in the chef/automate open-source repository here: https://github.com/chef/automate/blob/b0065dda66b8bcd0acc2568ed2e6fd04573979a1/components/automate-gateway/gateway/server.go#L248

I will add, though, that even the happy path like this...
<img width="555" alt="image" src="https://user-images.githubusercontent.com/6817500/110573129-90dfa300-810f-11eb-89d4-a7481ac9cd2b.png">

... can do with a bit of explanation in the docs.

**Comment by chmccreery** [comment]
From another user:

After I've installed it, it's a bit unclear how I am supposed to use it.
11:21
I see there is in the command palette two things I can run
11:21
But I guessed at looking there for them
11:22
(semgrep suggestion on line and autofix on file)
